version: "3"

services:
  sample-front:
    container_name: sample-front
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - sample-front-container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3030:3000"
      - "24678:24678"
    volumes:
      - ./:/work
    tty: true
    restart: always

networks:
  reverse-proxy-network:
    external: true