up:
	docker compose up -d --force-recreate
build:
	docker compose up -d --build
nest:
	docker compose exec nestjs sh
dev:
	docker compose exec nestjs yarn start:dev
pg:
	docker compose exec nestjs-postgres sh
