services:
  caddy:
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - reverse-proxy-container
    container_name: caddy
    image: caddy:2
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      - DOMAIN_KEYCLOAK=$DOMAIN_KEYCLOAK
      - TLS_EMAIL_KEYCLOAK=$TLS_EMAIL_KEYCLOAK
      - LOG_PATH_KEYCLOAK=$LOG_PATH_KEYCLOAK
      - HOSTNAME_KEYCLOAK=$HOSTNAME_KEYCLOAK
      - DOMAIN_NUXT=$DOMAIN_NUXT
      - TLS_EMAIL_NUXT=$TLS_EMAIL_NUXT
      - LOG_PATH_NUXT=$LOG_PATH_NUXT
      - HOSTNAME_NUXT=$HOSTNAME_NUXT
      - DOMAIN_NESTJS=$DOMAIN_NESTJS
      - TLS_EMAIL_NESTJS=$TLS_EMAIL_NESTJS
      - LOG_PATH_NESTJS=$LOG_PATH_NESTJS
      - HOSTNAME_NESTJS=$HOSTNAME_NESTJS

networks:
  reverse-proxy-network:
    external: true
